# Generated by Django 5.1.6 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deser_name', models.CharField(max_length=50)),
                ('deser_description', models.TextField()),
                ('fee', models.BigIntegerField()),
            ],
        ),
    ]
