# Generated by Django 5.1.6 on 2025-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desers_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deser',
            name='deser_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='deser',
            name='fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
