# Generated by Django 5.1.6 on 2025-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=50)),
                ('fee', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
