# Generated by Django 5.1.6 on 2025-02-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='fee',
        ),
    ]
