# Generated by Django 5.1.6 on 2025-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes_menu', '0002_remove_cafe_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_describtion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
