# Generated by Django 5.1.6 on 2025-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_deser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='describtion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deser',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
