# Generated by Django 5.1.6 on 2025-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_cafe_describtion_alter_deser_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deser',
            name='description',
        ),
        migrations.AddField(
            model_name='deser',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
